add_library(remi_gravity STATIC GravityGame.cpp)
target_include_directories(remi_gravity PUBLIC "${CMAKE_CURRENT_SOURCE_DIR}")
target_link_libraries(remi_gravity PUBLIC REMI::Physics PRIVATE remi_build_options)
add_executable(REMIGravity main.cpp)
target_link_libraries(REMIGravity PRIVATE remi_gravity REMI::Runtime REMI::Renderer REMI::Resources remi_build_options)
set_target_properties(REMIGravity PROPERTIES RUNTIME_OUTPUT_DIRECTORY "${CMAKE_BINARY_DIR}/bin/$<CONFIG>" VS_DEBUGGER_WORKING_DIRECTORY "$<TARGET_FILE_DIR:REMIGravity>")
add_dependencies(REMIGravity remi_sandbox_shaders)
